spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared #        git:#          uri: https://github.com/kasturibiswal/config1
#          skipSslValidation: true
#          username: 
#          password: '@kasamb1g'
  profiles:
    active: native 
#  security:
#    user:
#      password: clientpassword1 #the password which apps will use to access its configurations

server:
  port: 8888 #the port where the config-server will be acessible